services:
  emby:
    image: 'linuxserver/emby:${EMBY_IMAGE_VERSION:-latest}'
    restart: unless-stopped
    environment:
      - 'TZ=${TZ:-Asia/Shanghai}'
      - 'PUID=${PUID:-1000}'
      - 'PGID=${PGID:-100}'
    ports:
      - '8096:8096'
    volumes:
      - ${EMBY_VOLUME:-.}/conf:/config
      - ${EMBY_VOLUME:-.}/plugins:/app/emby/plugins
      - ${MEDIA_VOLUME:-/mnt/user/media}:/mnt/user/media
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['${GPU_DEVICE_ID:-0}']
              capabilities: [gpu]