services:
  xarr-rss:
    image: 'xiaoyi510/xarr-rss:${XARR_RSS_IMAGE_VERSION:-latest}'
    restart: unless-stopped
    environment:
      - 'TZ=${TZ:-Asia/Shanghai}'
      - 'PUID=${PUID:-1000}'
      - 'PGID=${PGID:-100}'
    ports:
      - '8086:8086'
    volumes:
      - ${XARR_RSS_VOLUME:-.}/conf:/app/conf
