services:
  sonarr-4k:
    image: 'linuxserver/sonarr:${SONARR_IMAGE_VERSION:-latest}'
    restart: always
    environment:
      - 'TZ=${TZ:-Asia/Shanghai}'
      - 'PUID=${PUID:-1000}'
      - 'PGID=${PGID:-100}'
    ports:
      - '8991:8989'
    volumes:
      - ${SONARR_4K_VOLUME:-.}/conf:/config
      - ${MEDIA_VOLUME:-/mnt/user/media}:/mnt/user/media
