services:
  jackett:
    image: 'linuxserver/jackett:${JACKETT_IMAGE_VERSION:-latest}'
    restart: always
    environment:
      - 'TZ=${TZ:-Asia/Shanghai}'
      - 'PUID=${PUID:-1000}'
      - 'PGID=${PGID:-100}'
    ports:
      - '9117:9117'
    volumes:
      - ${JACKETT_VOLUME:-.}/conf:/config
