services:
  jackett:
    image: 'linuxserver/jackett:${NGINX_PROXY_MANAGER_IMAGE_VERSION:-latest}'
    restart: unless-stopped
    environment:
      - 'TZ=${TZ:-Asia/Shanghai}'
      - 'PUID=${PUID:-1000}'
      - 'PGID=${PGID:-100}'
    ports:
      - '9117:9117'
    volumes:
      - ${NGINX_PROXY_MANAGER_VOLUME:-.}/conf:/config
