services:
  uptime-kuma:
    image: 'elestio/uptime-kuma:${UPTIME_KUMA_VERSION:-latest}'
    restart: unless-stopped
    environment:
      - 'TZ=${TZ:-Asia/Shanghai}'
      - 'PUID=${PUID:-1000}'
      - 'PGID=${PGID:-100}'
    ports:
      - '3001:3001'
    volumes:
      - ${UPTIME_KUMA_VOLUME:-.}/data:/app/data
