services:
  nginx-proxy-manager:
      image: 'jc21/nginx-proxy-manager:${NGINX-PROXY-MANAGER_IMAGE_VERSION:-latest}'
      restart: unless-stopped
      ports:
        - '80:80'
        - '81:81'
        - '443:443'
      volumes:
        - ./data:/data
        - ./letsencrypt:/etc/letsencrypt