services:
  jellyseerr:
    image: 'fallenbagel/jellyseerr:${JELLYSEERR_IMAGE_VERSION:-latest}'
    restart: always
    user: ${PUID:-1000}:${PGID:-100}
    environment:
      - 'TZ=${TZ:-Asia/Shanghai}'
      - 'JELLYFIN_TYPE=${JELLYSEERR_JELLYFIN_TYPE:-jellyfin}'
    ports:
      - '5055:5055'
    volumes:
      - ${JELLYSEERR_VOLUME:-.}/conf:/app/config
